{% set version = "0.8.2" %}

package:
  name: climlab
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/climlab/climlab-{{ version }}.tar.gz
  sha256: 0ddfd1a638b66bcfca40ed3e6eca0196bf5464b4e41b73fe77a6cb854360ca8c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.6
    - pooch
    - xarray
    - numpy
    - scipy
    - future
    - climlab-rrtmg
    - climlab-emanuel-convection
    - climlab-cam3-radiation
    - six

test:
  requires:
    - pytest
  imports:
    - climlab
  commands:
    - pytest -v -m fast --pyargs climlab

about:
  home: https://github.com/climlab/climlab
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python package for process-oriented climate modeling
  doc_url: http://climlab.readthedocs.io/
  dev_url: https://github.com/climlab/climlab

extra:
  recipe-maintainers:
    - brian-rose
    - jhkennedy
