{% set name = "climlab" %}
{% set version = "0.6.2" %}
{% set sha256 = "de518b1cb9c00b579531a33cb60483b31b5777b3f20a12181f6aab027bc094a8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2

requirements:
  build:
    - toolchain
    - mingwpy  # [win]
    - gcc  # [osx]
    - python
    - setuptools
    - libgfortran  # [linux]
    - numpy 1.11.*

  run:
    - python
    - numpy >=1.11
    - scipy
    - netcdf4
    - xarray
    - pytest
    - libgfortran  # [linux or osx]
    - future
    - numba  # [py2k]

test:
  requires:
    - pytest
  imports:
    - climlab
  commands:
    - pytest -v -m fast --pyargs climlab.tests

about:
  home: https://github.com/brian-rose/climlab
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python package for process-oriented climate modeling
  doc_url: http://climlab.readthedocs.io/
  dev_url: https://github.com/brian-rose/climlab

extra:
  recipe-maintainers:
    - brian-rose
