{% set version = "0.7.3" %}

package:
  name: climlab
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/climlab/climlab-{{ version }}.tar.gz
  sha256: ec647bd2041e724b27ec906f04f626cdbc66ddfa44edeec0782db420a5c73513

build:
  skip: True  # [win32 or (win and py27)]
  number: 0

requirements:
  build:
     - {{ compiler('fortran') }}
     - {{ compiler('c') }}
  host:
    - flang  # [win and py3k]
    - python
    - setuptools
    - pip
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - libflang  # [win and py3k]
    - scipy
    - pydap
    - requests
    - xarray
    - future
    - attrdict

test:
  requires:
    - pytest
  imports:
    - climlab
  commands:
    - pytest -v -m fast --pyargs climlab.tests

about:
  home: https://github.com/brian-rose/climlab
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python package for process-oriented climate modeling
  doc_url: http://climlab.readthedocs.io/
  dev_url: https://github.com/brian-rose/climlab

extra:
  recipe-maintainers:
    - brian-rose
