{% set version = "0.8.1" %}

package:
  name: climlab
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/climlab/climlab-{{ version }}.tar.gz
  sha256: b5ab8b68680e3ce7bece80ea9d15e9c30829ac40c9db6b09ec9c70b4a111d19e

build:
  number: 0
  skip: true  # [win and py<30]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('fortran') }}
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ compiler('c') }}
  host:
    - libpython  # [win]
    - python
    - setuptools
    - pip
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - pooch
    - xarray
    - future

test:
  requires:
    - pytest
  imports:
    - climlab
  commands:
    - pytest -v -m fast --pyargs climlab  # [python_impl != 'pypy']
    - pytest -v -m fast --pyargs climlab.tests.test_bandrc climlab.tests.test_cam3rad climlab.tests.test_domain2D climlab.tests.test_ebm climlab.tests.test_emanuel_convection climlab.tests.test_grey_radiation climlab.tests.test_rcm climlab.tests.test_rrtm climlab.tests.test_thermo climlab.tests.xarray_test  # [python_impl == 'pypy']

about:
  home: https://github.com/brian-rose/climlab
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python package for process-oriented climate modeling
  doc_url: http://climlab.readthedocs.io/
  dev_url: https://github.com/brian-rose/climlab

extra:
  recipe-maintainers:
    - brian-rose
    - jhkennedy
