{% set version = "0.7.13" %}

package:
  name: climlab
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/climlab/climlab-{{ version }}.tar.gz
  sha256: 0b9498bf6dd1ab97665cab34ce4602c1d781c3a6365cd243f53c1fa3af669c23

build:
  number: 0
  skip: true  # [win and py<30]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('fortran') }}
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ compiler('c') }}
  host:
    - m2w64-toolchain  # [win]
    - libpython  # [win]
    - python
    - setuptools
    - pip
    - numpy
    - gfortran 
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - pooch
    - xarray
    - future

test:
  requires:
    - pytest
  imports:
    - climlab
  commands:
    - pytest -v -m fast --pyargs climlab

about:
  home: https://github.com/brian-rose/climlab
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python package for process-oriented climate modeling
  doc_url: http://climlab.readthedocs.io/
  dev_url: https://github.com/brian-rose/climlab

extra:
  recipe-maintainers:
    - brian-rose
    - jhkennedy
