{% set version = "0.8.1" %}

package:
  name: climlab
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/climlab/climlab-{{ version }}.tar.gz
  sha256: b5ab8b68680e3ce7bece80ea9d15e9c30829ac40c9db6b09ec9c70b4a111d19e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.6
    - pooch
    - xarray
    - numpy
    - scipy
    - future
    - climlab-rrtmg
    - climlab-emanuel-convection
    - climlab-cam3-radiation
    - six

test:
  requires:
    - pytest
  imports:
    - climlab
  commands:
    - pytest -v -m fast --pyargs climlab
    - pytest -v -m fast --pyargs climlab.tests.test_bandrc climlab.tests.test_cam3rad climlab.tests.test_domain2D climlab.tests.test_ebm climlab.tests.test_emanuel_convection climlab.tests.test_grey_radiation climlab.tests.test_rcm climlab.tests.test_rrtm climlab.tests.test_thermo climlab.tests.xarray_test  # [python_impl == 'pypy']

about:
  home: https://github.com/climlab/climlab
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python package for process-oriented climate modeling
  doc_url: http://climlab.readthedocs.io/
  dev_url: https://github.com/climlab/climlab

extra:
  recipe-maintainers:
    - brian-rose
    - jhkennedy
