{% set version = "0.9.0" %}

package:
  name: climlab
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/climlab/climlab-{{ version }}.tar.gz
  sha256: 9e4205cf9dc37528911c3c59f0c770f2616ea75c07f833a44b2041cfa4e950b7

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - pooch
    - xarray
    - numpy
    - scipy >=1.6
    - future
    - climlab-rrtmg >=0.4.1
    - climlab-emanuel-convection
    - climlab-cam3-radiation >0.2
    - climlab-sbm-convection
    - six

test:
  requires:
    - pytest
    - python {{ python_min }}
  imports:
    - climlab
  commands:
    - pytest -v -m fast --pyargs climlab

about:
  home: https://github.com/climlab/climlab
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python package for process-oriented climate modeling
  doc_url: http://climlab.readthedocs.io/
  dev_url: https://github.com/climlab/climlab

extra:
  recipe-maintainers:
    - brian-rose
    - jhkennedy
